theme: jekyll-theme-minimal
title: Causal Incentives Working Group
description: We are a collection of researchers interested in using causal models to understand agent incentives, in order to design safe and fair AI algorithms. </br></br> If you are interested in collaborating on any related problems, feel free to reach out to us.

logo: logo.png
